## Metadata for ibm-transadv-dev configuration
## This metadata is used to augment the value.yaml to drive IPC UI for configuration of the Helm chart installation

## Architecture configuration metadata
## Arch metadata
arch:
  __metadata:
    label: "Architecture scheduling preferences"
  amd64:
    __metadata:
      name: "amd64"
      label: "AMD64 scheduling preference"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No preference"
        value: "2 - No preference"  
      - label: "3 - Most preferred"
        value: "3 - Most preferred"  
  ppc64le:
    __metadata:
      name: "ppc64le"
      label: "PPC64LE scheduling preference"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No preference"
        value: "2 - No preference"
      - label: "3 - Most preferred"
        value: "3 - Most preferred"

couchdb:
  ## Image configuration metadata
  image:
    repository:
      __metadata:
        name: "repository"
        label: "repository"
        description: "Docker image location"
        type: "string"
        immutable: false
        required: true
    pullPolicy:
      __metadata:
        name: "pullPolicy"
        label: "Docker image pull policy"
        description: "Always, Never, or IfNotPresent. Defaults to Always"
        type: "string"
        immutable: false
        required: true
        options:
        - label: "Always"
          value: "Always"
        - label: "Never"
          value: "Never"
        - label: "IfNotPresent"
          value: "IfNotPresent"  
    tag: 
      __metadata:
        name: "Docker image Tag"
        label: "Docker image Tag"
        description: "Docker image Tag"
        type: "string"
        immutable: false
        required: true
  ## Resource requests and limits configuration metadata
  resources:
    __metadata:
      label: "Resources"
    requests:
      cpu: 
        __metadata: 
          label: "CPU request"
          description: "The requested CPU"
          type: "string"
          required: true   
      memory: 
        __metadata: 
          label: "Memory request"
          description: "The memory request"
          type: "string"
          required: true   
    limits:
      cpu: 
        __metadata: 
          label: "CPU limit"
          description: "The CPU limit"
          type: "string"
          required: true   
      memory: 
        __metadata: 
          label: "Memory limit"
          description: "The memeory limit"
          type: "string"
          required: true   

  ## Persistence options
  persistence:
    __metadata:
      label: "Data persistence configuration"
    enabled:
     __metadata:
        name: "enabled"
        label: "Enable persistence for this deployment"
        description: "Enables persistence for this deployment. Defaults to true. A persistent volume is required."
        type: "boolean"
        immutable: "false"
        required: true
    accessMode:
      __metadata:
        name: "accessMode"
        label: "PVC access mode"
        description: "ReadWriteOnce, ReadOnlyMany, or ReadWriteMany."
        type: "string"
        immutable: false
        required: true
        options:
        - label: "ReadWriteOnce"
          value: "ReadWriteOnce"
        - label: "ReadOnlyMany"
          value: "ReadOnlyMany"
        - label: "ReadWriteMany"
          value: "ReadWriteMany"
    size:
      __metadata:
        name: "size"
        label: "Size of the volume claim"
        description: "Defaults to 20Gi of storage request. Choose a different size of disk if needed."
        type: "string"
        immutable: "false"
        required: true
    useDynamicProvisioning:
     __metadata:
        name: "useDynamicProvisioning"
        label: "Use dynamic provisioning for persistent volume"
        description: "If dynamic provisioning is available in the cluster this option will automatically provision the requested volume if set to true. Defaults to true."
        type: "boolean"
        immutable: "false"
        required: true
    existingClaim:
      __metadata:
        name: "existingClaim"
        label: "Existing volume claim"
        description: "By default a new persistent volume claim will be created. Specify an existing claim here if one is available."
        type: "string"
        immutable: "false"
        required: false
    storageClassName:
      __metadata:
        name: "storageClassName"
        label: "Existing storage class name"
        description: "Choose a specific storage class name. Defaults to the default storage class in the cluster."
        type: "string"
        immutable: "false"
        required: false

transadv:
  ## Image configuration metadata
  image:
    repository:
      __metadata:
        name: "repository"
        label: "repository"
        description: "Docker image location"
        type: "string"
        immutable: false
        required: true
    pullPolicy:
      __metadata:
        name: "pullPolicy"
        label: "Docker image pull policy"
        description: "Always, Never, or IfNotPresent. Defaults to Always"
        type: "string"
        immutable: false
        required: true
        options:
        - label: "Always"
          value: "Always"
        - label: "Never"
          value: "Never"
        - label: "IfNotPresent"
          value: "IfNotPresent"  
    tag: 
      __metadata:
        name: "Docker image Tag"
        label: "Docker image Tag"
        description: "Docker image Tag"
        type: "string"
        immutable: false
        required: true
  ## Service configuration metadata
  service:
    nodePort:
      __metadata:
        name: "externalPort"
        label: "External port"
        description: "This is the external port number"
        type: "number"
        immutable: false
        required: true
  ## Resource requests and limits configuration metadata
  resources:
    __metadata:
      label: "Resources"
    requests:
      cpu: 
        __metadata: 
          label: "CPU request"
          description: "The requested CPU"
          type: "string"
          required: true   
      memory: 
        __metadata: 
          label: "Memory request"
          description: "The memory request"
          type: "string"
          required: true   
    limits:
      cpu: 
        __metadata: 
          label: "CPU limit"
          description: "The CPU limit"
          type: "string"
          required: true   
      memory: 
        __metadata: 
          label: "Memory limit"
          description: "The memeory limit"
          type: "string"
          required: true   

transadvui:
  ## Image configuration metadata
  image:
    repository:
      __metadata:
        name: "repository"
        label: "repository"
        description: "Docker image location"
        type: "string"
        immutable: false
        required: true
    pullPolicy:
      __metadata:
        name: "pullPolicy"
        label: "Docker image pull policy"
        description: "Always, Never, or IfNotPresent. Defaults to Always"
        type: "string"
        immutable: false
        required: true
        options:
        - label: "Always"
          value: "Always"
        - label: "Never"
          value: "Never"
        - label: "IfNotPresent"
          value: "IfNotPresent"  
    tag: 
      __metadata:
        name: "Docker image Tag"
        label: "Docker image Tag"
        description: "Docker image Tag"
        type: "string"
        immutable: false
        required: true
  ## Service configuration metadata
  service:
    nodePort:
      __metadata:
        name: "externalPort"
        label: "External port"
        description: "This is the external port number"
        type: "number"
        immutable: false
        required: true
  ## Resource requests and limits configuration metadata
  resources:
    __metadata:
      label: "Resources"
    requests:
      cpu: 
        __metadata: 
          label: "CPU request"
          description: "The requested CPU"
          type: "string"
          required: true   
      memory: 
        __metadata: 
          label: "Memory request"
          description: "The memory request"
          type: "string"
          required: true   
    limits:
      cpu: 
        __metadata: 
          label: "CPU limit"
          description: "The CPU limit"
          type: "string"
          required: true   
      memory: 
        __metadata: 
          label: "Memory limit"
          description: "The memeory limit"
          type: "string"
          required: true   

